#!/bin/bash
echo "cloud-init cnvr running on hostname $(uname -n)"

curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install -y nodejs

git clone https://github.com/jirojo2/cnvr-os-deploy.git /opt

pushd /opt/www
npm install
npm install -g forever
PORT=80 MONGO=mongodb://10.1.1.5/cnvr forever start app.js
popd
exit 0
